### ISSUE TITLE
stakerPendingReward Weird Value Issue On Shibuya Testnet.

### ISSUE THREAD

**Issue by johnnyji-dev** [AstarNetwork/astar.js#49]
**Describe the bug**
I just created wallet address and requested pending reward value by using "estimatePendingRewards" from '@astar-network/astar-sdk-core'.
I have not been staking before.
So weird point that I expected the pending reward obviously 0.
But I returned 3 on shibuya testnet.
Also I can't retrieve any other information on "shibuya.subscan.io".

The wallet address is "bdxjY4YMr5smwB5hc4k6zZAEnFGCak39AcZCZ8e4eY4B4Am".
`
const estimatedReward = await estimatePendingRewards({
        api: this.client, // shibuya endpoint
        walletAddress: "bdxjY4YMr5smwB5hc4k6zZAEnFGCak39AcZCZ8e4eY4B4Am"
})
return estimatedReward;
`

Why does it happened?
Can it be fixed? Or Is it Okay on mainnet?
Thx~

**Comment by impelcrypto** [comment]
Hi @johnnyji-dev 
It seems that the address of 'bdxjY4YMr5smwB5hc4k6zZAEnFGCak39AcZCZ8e4eY4B4Am' has eras you haven't claimed yet. Perhaps you withdrew it before claiming rewards.

<img width="1716" alt="image" src="https://github.com/AstarNetwork/astar.js/assets/92044428/f3e42f5a-3330-4cee-a6f5-fddc617fbc24">

**Comment by johnnyji-dev** [comment]
@impelcrypto 
How can you get staking history?
That walllet address didn't have any transaction history on below shibuya.subscan.io.
https://shibuya.subscan.io/account/bdxjY4YMr5smwB5hc4k6zZAEnFGCak39AcZCZ8e4eY4B4Am

Obivously, I think that I just created wallet by polkadot.js lib and than did no action on this wallet.

I also tried to retrieve same action but in my case have no data.
![image](https://github.com/AstarNetwork/astar.js/assets/125259310/961a386f-8829-4829-aa5a-cc8b31acd11d)

**Comment by impelcrypto** [comment]
@johnnyji-dev 
It seems that Polkadot.js occur an error for this as If I input the exact address, but also specify the smart contract address, I got an empty value (no stakes). Perhaps you can try creating new account and see the result. Thanks.

![image](https://github.com/AstarNetwork/astar.js/assets/92044428/158bf433-1d23-4fec-991f-81763d196dad)

**Comment by johnnyji-dev** [comment]
> @johnnyji-dev It seems that Polkadot.js occur an error for this as If I input the exact address, but also specify the smart contract address, I got an empty value (no stakes). Perhaps you can try creating new account and see the result. Thanks.
> 
> ![image](https://user-images.githubusercontent.com/92044428/242541385-158bf433-1d23-4fec-991f-81763d196dad.png)

I tried more.

![image](https://github.com/AstarNetwork/astar.js/assets/125259310/2dab24f2-36d2-4eb6-a9f8-58e7c00a3422)

===

![image](https://github.com/AstarNetwork/astar.js/assets/125259310/fa884dbf-62cd-4157-82b3-e0a75c5d57cb)

===

![image](https://github.com/AstarNetwork/astar.js/assets/125259310/806bd5ce-ccf7-4520-b804-9be1e62bfd7f)

**Comment by impelcrypto** [comment]
Yes, and you can try with creating new accounts
