### ISSUE TITLE
Module not found: Can't resolve imported dependency "@astar-network/astar-api"

### ISSUE THREAD

**Issue by sirius651** [AstarNetwork/astar.js#7]
**Describe the bug**
when I try to use `import { options } from '@astar-network/astar-api';`, it causes
```
Module not found: Can't resolve imported dependency "@astar-network/astar-api"
```

**Comment by drewstone** [comment]
Can you provide details on your setup and steps to reproduce?

**Comment by drewstone** [comment]
As far as I know @sirius651, the examples work with this type of dependency so it might be an issue with your `tsconfig.json`.

https://github.com/webb-tools/astar.js/blob/main/examples/index.ts

**Comment by sirius651** [comment]
@drewstone  I just installed as `yarn add @astar-network/astar-api` , then add `import { options } from '@astar-network/astar-api';`. 
here's our `tsconfig.json`: https://github.com/AstarNetwork/astar-apps/blob/main/tsconfig.json  
What parameters should we put in to match compatibility? other third party library works smoothly without custom config though

**Comment by sirius651** [comment]
@drewstone Hello, any news for this?

**Comment by drewstone** [comment]
We will have @sushi30 look into this and fix it up.

**Comment by sushi30** [comment]
Hi. I updated the npm package. Please try reinstalling using the command in the README. Not that you might have to reinstall astar-api

```shell
yarn up @astar-network/astar-api@beta
```

**Comment by sirius651** [comment]
Thanks, it works now
