### ISSUE TITLE
"api.query.dappsStaking.generalEraInfo.entries()" is undefined, is it deprecated ? How can I get currentEra Info?

### ISSUE THREAD

**Issue by johnnyji-dev** [AstarNetwork/astar.js#72]
After V3 upgrade, my-api server have some issue.

I can get Era info by using "dappsStaking-api etc".

```
    async getCurrentEra(): Promise<any> {
        try {
            const eraInfo = await this.client.query.dappsStaking.generalEraInfo.entries()
            Logger.debug(`eraInfo : ${eraInfo}`)

            const eraTvls = formatEraTvls(eraInfo)
            Logger.debug(`eraTvls : ${eraTvls}`)

            const currentEra = eraTvls[eraTvls.length -1].era;
            Logger.debug(`currentEra : ${currentEra}`)
            return currentEra;
        } catch (error) {
            Logger.error(`errCode:${error.code} | errMsg:${error.message}`);
            throw new ApplicationException(error.code, error.message);
        }
    }
```
On that code, return error( Cannot read properties of undefined (reading 'generalEraInfo') )...

On github code, "generalEraInfo" is existed yet!

How can I get current era by calling api?

What version of AstarNode is needed? Over 5.32.0? (https://github.com/AstarNetwork/Astar/releases/tag/v5.32.0)

**Comment by bobo-k2** [comment]
Try with

```
this.client.query.dappStaking.activeProtocolState()
```

V3 runtime is not compatibile with v2. If you want to get more info on how to use dApp staking from the client perspective check https://github.com/AstarNetwork/astar-apps/tree/main/src/staking-v3

**Comment by johnnyji-dev** [comment]
> Try with
> 
> ```
> this.client.query.dappStaking.activeProtocolState()
> ```
> 
> V3 runtime is not compatibile with v2. If you want to get more info on how to use dApp staking from the client perspective check https://github.com/AstarNetwork/astar-apps/tree/main/src/staking-v3

@bobo-k2 It's very helpful for ur feedback~~ so so thx!!

I have additional **_questions more about controlling(transfer or staking etc) my balance._**
After upgrade V3, I wonder how to check out a **_account-balance (Transferable, Staking, Unstaking, etc)._**

For example, I can retrieve my balance(a7ZEP29Zk9vrfNWiENXdhLQWxp3yVSvaTBtTcJAkDKHijwX) account by [subscan.io](https://astar.subscan.io/account/a7ZEP29Zk9vrfNWiENXdhLQWxp3yVSvaTBtTcJAkDKHijwX).
![image](https://github.com/AstarNetwork/astar.js/assets/125259310/12d90406-d7c2-425b-93c9-ee16a271bfc0)

The account was staking about 1000 ASTR(maybe, not matter that number) on V2.
And I didn't unstake ahead on V2.
I took a look ur description about V3. It said that staking amount will be unstaked and locked.

Q1) Does it mean that my staked amount before V3(on V2) is locked and it need to wait 10-era to do "withdraw_unbonded"-tx for transit transferable amount? That is right? But on subscan(above picture) it looks like already on tranferable state.

Above all, by using polkadot.js and astar.js api, I tried to get some balance and staking and lockedInfo like belows.
Q2) How can I got that meaning of balance?

Q2-1) "subscan" said that my transferable amount is 1129 ASTR but "balance-API" said that miscFrozen(I understand that miscFrozen is locking amount) is 1000.xx ASTR. Which one is correct?

Q2-2) How can I unlock the locked amount? Just wait for 10-era and tried to broadcast "withdraw_unbonded"-tx?

Q2-3) I tried to stake([tx-subscan](https://astar.subscan.io/account/a7ZEP29Zk9vrfNWiENXdhLQWxp3yVSvaTBtTcJAkDKHijwX)) 1000 ASTR by portal(portal.astar.network). By the way, on subscan the amount is not display on staking section, still on transferable.
It's so weird... I don't know how to interpret this situation.
![Monosnap astarsubstrate service ts — crypto-grid  개발 컨테이너: crypto-grid  2024-02-14 15-36-00](https://github.com/AstarNetwork/astar.js/assets/125259310/97eb26e9-cd86-481a-84bb-9188043d944d)

Q3) I wanna know how to fix to get stakingInfo.
Below picture is my ASIS api-method for retrieving [stakingInfo].
(address : a7ZEP29Zk9vrfNWiENXdhLQWxp3yVSvaTBtTcJAkDKHijwX)(https://astar.subscan.io/extrinsic/0xb1192ab5d1311f59e022d106a0c2edf3a506ca7d767cc7b7ac363385aba6af99) after V3 upgrade.
![image](https://github.com/AstarNetwork/astar.js/assets/125259310/fe66a8cd-b034-4abc-a0d3-f8252dcf1c89)

Q4) I wanna know how to fix to get lockedUnbondingInfo.
Below picture is my ASIS api-method for retrieving [lockedUnbondingInfo].
(address : WDQ2Cv41nsn82t4K4Mv4DiAGiTbwhbs4YkS3fWZSGBG8mqZ)
![image](https://github.com/AstarNetwork/astar.js/assets/125259310/261de941-b577-4d60-b1df-a6437729aeab)

Q5) I wanna know how to fix to get dAppInfo.
Below picture is my ASIS api-method for retrieving [dAppInfo].
![image](https://github.com/AstarNetwork/astar.js/assets/125259310/94df4e07-2162-480a-99ef-1313d0505096)

For Q3~5,
I tried to check out V3-runtime(https://github.com/AstarNetwork/astar-apps/tree/main/src/staking-v3) before you let me know, but I can't convince which one is correct?

Thx~!

**Comment by bobo-k2** [comment]
Hi, a lot of question are answered in Astar docs and the portal source code. Please refer to documentation and Astar portal source code first and in case you can't find answer there I will try to help

https://docs.astar.network/docs/learn/dapp-staking/
https://docs.astar.network/docs/use/dapp-staking/
https://docs.astar.network/docs/build/dapp-staking/

https://github.com/AstarNetwork/astar-apps/tree/main/src/staking-v3

**Comment by johnnyji-dev** [comment]
> Hi, a lot of question are answered in Astar docs and the portal source code. Please refer to documentation and Astar portal source code first and in case you can't find answer there I will try to help
> 
> https://docs.astar.network/docs/learn/dapp-staking/ https://docs.astar.network/docs/use/dapp-staking/ https://docs.astar.network/docs/build/dapp-staking/
> 
> https://github.com/AstarNetwork/astar-apps/tree/main/src/staking-v3

thx~! very helpful
